name: Run Spectral on Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

jobs:
  build:
    name: Run Spectral validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'bkg/v1/bkg.yaml'
          spectral_ruleset: '.stoplight/styleguide.json'